services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      ARGUMENTS: "-device usb-host,vendorid=0x0483,productid=0xa0cb"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./windows:/storage
      - /home/falk/.local/share/windows-vm-shared:/shared
