# Wayland (native)
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--enable-wayland-ime
--wayland-text-input-version=3
--enable-features=WaylandWindowDecorations
--enable-features=VaapiVideoDecoder
--ignore-gpu-blocklist

# WebBluetooth on Linux (still gated behind “experimental web platform features”)
--enable-experimental-web-platform-features
--enable-feature=WebBluetooth
