# Wayland (native)
--enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder,WebBluetooth
--ozone-platform=wayland
--enable-wayland-ime
--wayland-text-input-version=3
--ignore-gpu-blocklist

# WebBluetooth on Linux (still gated behind "experimental web platform features")
--enable-experimental-web-platform-features
