# Wayland (native)
# WebBluetooth disabled because it can keep BlueZ discovery scanning.
# --enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder,WebBluetooth
--enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder
--ozone-platform=wayland
--enable-wayland-ime
--wayland-text-input-version=3
--ignore-gpu-blocklist

# --enable-experimental-web-platform-features
